chap/Admin/Admin/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('Auth/',include('Auth.urls')),
    path('',views.home_page,name='home'),
    path('CreateDb',include('CreateDb.urls'))

]
#urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

chap/Admin/Auth/urls.py
from django.urls import path
app_name="Auth"
from . import views
urlpatterns=[
path('login_page',views.login_page,name='Login'),
path('signup_page',views.signup_page,name='Signup'),
path('logout_page',views.logout_page,name='Logout')
]

chap/Admin/CreateDb/urls.py
from django.urls import path
app_name="CreateDb"
from .import views
urlpatterns=[
path('',views.model_form_upload,name="CreateDb")
] 

chap/Admin/CreateDb/models.py
from django.db import models

# Create your models here.
class Document(models.Model):
	document=models.FileField(upload_to='documents/')

chap/Admin/CreateDb/forms.py
from django import forms
from . import models
class DocumentForm(forms.ModelForm):
	class Meta:
		model = models.Document
		fields=('document',)

chap/Admin/Admin/views.py
from django.shortcuts import render
def home_page(request):
	return render(request,'base.html')

chap/Admin/CreateDb/views.py
from django.shortcuts import render,redirect
from .forms import DocumentForm

# Create your views here.
def CreateDb(request):
	return render(request,'CreateDb/create.html')
def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = DocumentForm()
    return render(request, 'CreateDb/model_form_upload.html', {
        'form': form
    })

chap/Admin/CreateDb/templates/CreateDb/create.html
{% extends 'base.html'%}
{%block content%}
<h1>Hello</h1>
{%endblock%}

chap/Admin/CreateDb/templates/CreateDb/model_form_upload.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

chap/Admin/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>chap</title>
</head>
<body>
	<header>
<h1><a href="{% url 'home' %}">Home</a></h1>
<h1>No gAp ONly CHap</h1>
</header>
<nav>
	<ul>
		{% if user.is_authenticated%}
		<li>
		<form class="site-form" action="{% url 'Auth:Logout'%}" method="POST">
			{% csrf_token%}
			<button type="submit">Logout</button>
			
		</form>
	</li>
	<li><a href="{% url 'CreateDb:CreateDb'%}">CreateDb</a></li>
	{%else%}
	<li><a href="{% url 'Auth:Login'%}">Login</a></li>
	<li><a href="{% url 'Auth:Signup' %}">Signup</a></li>
	{%endif%}
</ul>
</nav>
<div>
	{%block content%}
	{%endblock%}
</div>
</body>
</html>